    
    
    </main>
    <footer class="container-fluid">
      <div class="bg-warning bg-subtle text-center">
        <address>
          <strong>Legendary Motorsport</strong>
          <br>
            " 4 DE ABRIL 1112 "
          <br>
            " Tandil, Argentina "
          <br>
          <abbr title="Phone">Nuestro contacto</abbr>
            " 2494578691 "
        </address>
        <address>
          <strong>Legendary Motorsport</strong>
          <br>
          <a href="#">LegendaryMotorsport@gmail.com</a>
        </address>
      </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>