<!DOCTYPE html>
<html lang="en">

<!-- head -->
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>Legendary Motorsport</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand h1" href="">Legendary Motorsport</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse position-absolute top-0 end-0" id="navbarNav">
                    <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="home">Home</a>
                            </li>
                            <li class="nav-item dropdown" id="bycategoria">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                </a>
                                <ul class="dropdown-menu dropdown-menu-dark">
                                    <div class="col-md-6"> 
                                        <select name="showByCategoria">
                                            <?php foreach ($categoria as $categorias) : ?>
                                                <option value="<?= $categorias->IDcategoria ?>">
                                                    <?php echo $categorias->categorias ?>
                                                </option>                           
                                            <?php endforeach ?>
                                        </select>   
                                </ul> 
                            </li>
                        <?php if (!isset($_SESSION['USER_ID'])) : ?>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="login">Login</a>
                            </li>
                        <?php else : ?>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="editarproductos">Seccion Editar Productos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="editarcategorias">Seccion Editar Categorias</a>
                            </li>
                            <li class="nav-item">
                                <?= $_SESSION['USER_EMAIL'] ?>
                                <a class="nav-link" aria-current="page" href="logout">Logout (<?= $_SESSION['USER_EMAIL'] ?>)</a>
                            </li>
                        <?php endif ?>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main class="container mt-5 mb-5">