<?php require './templates/header.phtml' ?>

<?php require_once './templates/agregar.producto.phtml' ?>
<?php require_once './templates/editar.producto.phtml' ?>

<table class="table">

    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Producto</th>
            <th scope="col">Talle</th>
            <th scope="col">Precio</th>
            <th scope="col">Cat</th>
            <th scope="col">Marca</th>
            <th scope="col">acciones</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($productos as $producto): ?>
            <tr>
                <th scope="row"><?= $producto->id_producto ?></th>
                <td><?= $producto->Producto ?></td>
                <td><?= $producto->Talle ?></td>
                <td><?= $producto->Precio ?></td>
                <td><?= $producto->categoria ?></td>
                <td><?= $producto->marca ?></td>
                <td>
                    <a href="eliminarProducto/<?= $producto->id_producto ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>
                </td>   
            </tr>
        <?php endforeach ?>
    </tbody>
   

</table>

<p class="mt-3"><small>Mostrando <?=$count?> productos</small></p>

<?php require './templates/footer.phtml' ?>