<?php require './templates/header.phtml' ?>

<section id="ShowByCategoria"> 
    <?php require './templates/carrousel.phtml' ?>
    <div class="container-fluid">
        <div class="row">
            <?php foreach($producto as $productoa): ?>
                <div class="col-md-4 mb-4 text-center">
                    <div class="card" style="width: 18rem;">
                        <img src="..." class="card-img-top" alt="...">
                        <div class="card-body">
                        <?php if ($producto->categoria = 'categoriaFiltro') ?>
                            <p class="card-text"><?= $producto->Producto ?></p>
                            <p class="card-text">$<?= $producto->Precio ?></p>
                            <a href="#pricing" class="btn btn-secondary btn-lg">Comprar</a>
                        </div>
                    </div>
                </div>
            <?php endforeach ?>
        </div>
    </div>
</section>



<?php require './templates/footer.phtml' ?>